# -*- coding: utf-8 -*-
"""Ativi/CEPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9SHhyNoG_3JfBLQplYhn_LnnFMaU7PU
"""

import requests
#https://viacep.com.br/ws/03282000/json
def main():
  print('CEPython')

  cep = input('Digite o CEP para a consulta: ')

  while len(cep) != 8 or cep != int:
    print('Quantidae de dígitos inválida!!!!!!')
    cep = input('Digite o CEP para a consulta: ')

  request = requests.get(f'https://viacep.com.br/ws/{cep}/json')
  endereco = request.json()

  if 'erro' not in endereco:
    print('==> CEP ENCONTRADO <==')

    print('CEP: {}'.format(endereco['cep']))
    print('Logradouro: {}'.format(endereco['logradouro'])) 
    print('Complemento: {}'.format(endereco['complemento'])) 
    print('Bairro: {}'.format(endereco['bairro'])) 
    print('Cidade: {}'.format(endereco['localidade'])) 
    print('Estado: {}'.format(endereco['uf'])) 

  else:
    print(f'{cep}: CEP inválido.')

  print('----------------------------')
  opcao = int(input('Deseja realizar outro consulta ?\n1. Sim\n2. Sair\n'))
  if opcao == 1:
    main()
  else:
    print('Até mais!!!')  
if __name__=='__main__':
  main()
