# -*- coding: utf-8 -*-
"""CEPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qK-2fzuXgVs_eE6qRcorvLvm-xWnHbcp
"""

import requests

def main():
	print('CEPython')

	cep = input('Digite o CEP para a consulta: ')

'''
while do nino ! Congrats for your resolution!!!! X2
'''

	while len(cep) != 8 or cep != int :
	#if len(cep) != 8:
		print('Quantidade de dígitos inválida!')
		cep = input('Digite o CEP para a consulta: ')
		#exit()

	request = requests.get('https://viacep.com.br/ws/{}/json/'.format(cep))

	endereco = request.json()


	if 'erro' not in endereco:
		print('==> CEP ENCONTRADO <==')

		print('CEP: {}'.format(endereco['cep']))
		print('Logradouro: {}'.format(endereco['logradouro']))
		print('Complemento: {}'.format(endereco['complemento']))
		print('Bairro: {}'.format(endereco['bairro']))
		print('Cidade: {}'.format(endereco['localidade']))
		print('Estado: {}'.format(endereco['uf']))
		
	else:
		print('{}: CEP inválido.'.format(cep))

	print('---------------------------------')
	opcao = int(input('Deseja realizar outra consulta ?\n1. Sim\n2. Sair\n'))
	if opcao == 1:
		main()
	else:
		print('Até mais!!!')

if __name__ == '__main__':
	main()
